[tool.poetry]
name = "promptio"
version = "0.1.0"
description = ""
authors = ["Nithya <nithya@aity.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gradio = "^5.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
